#!/usr/bin/env node
/**
 * Token build pipeline.
 *
 * Reads DTCG v1 JSON from `tokens/` (primitive → semantic → component) and emits
 * `styles/tokens.css` with:
 *   - An `@theme { … }` block (Tailwind v4 CSS-first config)
 *   - `[data-theme="light"]` / `[data-theme="dark"]` / `[data-contrast="more"]` scoped blocks
 *
 * Mode overrides are declared under each token's `$extensions.modes.{dark|high-contrast}.$value`.
 * The script tolerates missing token files (Phase 1 Task 2 state — files arrive in Tasks 3, 4).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(__dirname, 'tokens');
const OUT = join(__dirname, 'styles/tokens.css');
const FILES = ['primitive.tokens.json', 'semantic.tokens.json', 'component.tokens.json'];
const MODES = ['dark', 'high-contrast'];

function loadTokens() {
  const acc = {};
  for (const f of FILES) {
    const path = join(TOKENS_DIR, f);
    if (!existsSync(path)) continue;
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    deepMerge(acc, raw);
  }
  return acc;
}

function deepMerge(a, b) {
  for (const k of Object.keys(b)) {
    if (a[k] && typeof a[k] === 'object' && !Array.isArray(a[k]) && typeof b[k] === 'object') {
      deepMerge(a[k], b[k]);
    } else {
      a[k] = b[k];
    }
  }
}

function flatten(tree, prefix = '') {
  const out = {};
  for (const [k, v] of Object.entries(tree)) {
    if (!v || typeof v !== 'object') continue;
    if ('$value' in v) {
      out[prefix ? `${prefix}.${k}` : k] = v;
    } else {
      Object.assign(out, flatten(v, prefix ? `${prefix}.${k}` : k));
    }
  }
  return out;
}

function varName(path) {
  return '--' + path.replace(/\./g, '-');
}

function resolve(value, flat, seen = new Set()) {
  if (typeof value !== 'string') return value;
  const m = value.match(/^\{([^}]+)\}$/);
  if (!m) return value;
  const key = m[1];
  if (seen.has(key)) {
    throw new Error(`Circular alias: ${[...seen, key].join(' → ')}`);
  }
  if (!(key in flat)) {
    throw new Error(`Unresolved alias: {${key}}`);
  }
  seen.add(key);
  return resolve(flat[key].$value, flat, seen);
}

function formatValue(v) {
  if (typeof v === 'object' && v !== null) return JSON.stringify(v);
  return String(v);
}

function emitBlock(selector, entries) {
  if (entries.length === 0) return '';
  const body = entries.map(([n, v]) => `  ${n}: ${v};`).join('\n');
  return `${selector} {\n${body}\n}\n`;
}

function build() {
  const tokens = loadTokens();
  const flat = flatten(tokens);

  const modeMap = { default: [], dark: [], 'high-contrast': [] };

  for (const [path, token] of Object.entries(flat)) {
    const defaultVal = resolve(token.$value, flat);
    modeMap.default.push([varName(path), formatValue(defaultVal)]);

    const modes = token.$extensions?.modes;
    if (!modes) continue;
    for (const mode of MODES) {
      const modeVal = modes[mode]?.$value;
      if (modeVal === undefined) continue;
      const resolved = resolve(modeVal, flat);
      modeMap[mode].push([varName(path), formatValue(resolved)]);
    }
  }

  const header =
    '/* Generated by build-tokens.mjs — do not edit. Source: tokens/*.tokens.json */\n\n';
  const themeBlock = emitBlock('@theme', modeMap.default) || '@theme {\n}\n';
  const lightBlock = emitBlock('[data-theme="light"], :root', modeMap.default);
  const darkBlock = emitBlock('[data-theme="dark"]', modeMap.dark);
  const hcBlock = emitBlock('[data-contrast="more"]', modeMap['high-contrast']);

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(
    OUT,
    header + themeBlock + '\n' + lightBlock + '\n' + darkBlock + '\n' + hcBlock,
    'utf8',
  );
  console.log(`✓ Wrote ${OUT}`);
  console.log(`  default (@theme + :root): ${modeMap.default.length} vars`);
  console.log(`  dark:    ${modeMap.dark.length} vars`);
  console.log(`  high-contrast: ${modeMap['high-contrast'].length} vars`);
}

build();
